[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=debug
pidfile=/var/run/supervisord.pid

[program:streamlit]
command=streamlit run /app/app/main.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:ollama]
command=/bin/sh -c "ollama serve & sleep 5 && ollama pull llama3.2:1b >> /var/log/ollama.log 2>&1 && ollama pull gemma3:1b >> /var/log/ollama.log 2>&1 && ollama pull deepseek-r1:1.5b >> /var/log/ollama.log 2>&1 && ollama pull qwen2.5:0.5b >> /var/log/ollama.log 2>&1 && tail -f /dev/null"
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr