[supervisord]
nodaemon=true

[program:streamlit]
command=streamlit run /app/main.py --server.port=8501 --server.address=0.0.0.0
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:ollama]
command=/bin/sh -c "ollama run llama3.2:1b && ollama run gemma3:1b && ollama run deepseek-r1:1.5b && ollama run qwen2.5:0.5b && tail -f /dev/null"
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr